server:
#  port: ${random.int[10000,19999]}
  port: 8011
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: orderserver
