# 在这里声明当前是开发环境或生产环境（dev or produce）
spring:
  profiles:
    active: dev

# 这里的配置不区分环境
guava:
  initNum: 10
  threadProfix: guava_thread_
  type: singleThread

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  type-aliases-package: cn.blysin.springboot.domain




---
# 开发环境下的配置

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

blysin:
  debugger: false
  name: 现在是开发环境



---
# 生产环境下的配置

spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

blysin:
  debugger: true
  name: 现在是生产环境
